### ISSUE TITLE
Contradiction in license

### ISSUE THREAD

**Issue by vargenau** [hesa/spdx-validator#37]
On page: https://pypi.org/project/spdx-validator/

You have both:

- Licence : GNU General Public License v3 or later (GPLv3+)
- The program is licensed under GPL-3.0-only

Which one is correct?

**Comment by hesa** [comment]
Thanks for pointing it out

It should be "or-later". 

Fixed with in main branch: https://github.com/hesa/spdx-validator/commit/4b81a7c0e3d7a043892cd373711dc50fb794c007
